{% set name = "occt" %}
{% set version = "7.6.0" %}
{% set build_number = 1 %}
{% set build_number = build_number + 0 %}    # [build_variant == "egl"]
{% set build_number = build_number + 100 %}  # [build_variant == "osmesa"]
{% set build_number = build_number + 200 %}  # [build_variant == "qt"]

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=V{{ version.replace(".", "_") }};sf=tgz
  sha256: b5484b6b7d2a15c2903ddc264b89e4e024f6f67bbbf28badfa773ec72a793279
  patches:
    #- no-xmu.patch
    #- error-checking.patch
    #- ShapeUpgrade.patch
    #- fix-step-import.patch

build:
  number: {{ build_number }}
  string: {{ build_variant }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build_number }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake 3.18
    - ninja
    - {{ cdt('mesa-libgl-devel') }}   # [linux and build_variant != "osmesa"]
    - {{ cdt('libxi-devel') }}        # [linux and build_variant != "osmesa"]
    - {{ cdt('libxext-devel') }}      # [linux and build_variant != "osmesa"]
    - {{ cdt('mesa-libegl-devel') }}  # [build_variant == "egl"]
    - {{ cdt('mesa-libgbm') }}        # [build_variant == "egl"]
    - {{ cdt('libxfixes') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libxcb') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libxau') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libuuid') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libxext') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libxfixes') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libxxf86vm') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libxdamage') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libselinux') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libsm-devel') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libice-devel') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('libx11-devel') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('mesa-libgl-devel') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('mesa-dri-drivers') }}  # [linux and build_variant != "osmesa"]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux and build_variant != "osmesa"]

  host:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - vtk * {{ build_variant }}*
    - rapidjson
  run:
    - freetype
    - freeimage
    - fontconfig
    - xorg-libxt  # [linux]
    - vtk * {{ build_variant }}*
    - rapidjson
test:
  requires:
    - ninja
    - cmake
  files:
    - CMakeLists.txt
  commands:
    - cmake -G "Ninja" .

about:
  home: https://www.opencascade.com/
  license_family: LGPL
  license: LGPL-2.1-only
  license_file: LICENSE_LGPL_21.txt
  summary: this is the occ (opencascade) CAD-Kernel
  description: |
    Open Cascade Technology (OCCT), formerly called CAS.CADE
    is an open source software development platform for 3D CAD,
    CAM, CAE, etc. that is developed and supported by Open Cascade SAS.
  doc_url: https://www.opencascade.com/content/documentation
  dev_url: http://git.dev.opencascade.org/gitweb/?p=occt.git

extra:
  recipe-maintainers:
    - looooo
